import { TownConfig } from '../types';
import { Business, Sector, Job, Event, Classified, Property, Announcement, Special } from '../../types';

// Menlyn Sectors (same structure, urban focus)
const MENLYN_SECTORS: Sector[] = [
  { id: 'home-services', name: 'Home Services', icon: '🏠' },
  { id: 'automotive', name: 'Automotive', icon: '🚗' },
  { id: 'health-wellness', name: 'Health & Wellness', icon: '🌿' },
  { id: 'food-drinks', name: 'Food & Drinks', icon: '🍴' },
  { id: 'shopping-retail', name: 'Shopping & Retail', icon: '🛍️' },
  { id: 'professional-services', name: 'Professional Services', icon: '⚖️' },
  { id: 'construction-industrial', name: 'Construction & Industrial', icon: '🏗️' },
  { id: 'education-community', name: 'Education & Community', icon: '🎓' },
  { id: 'tourism-hospitality', name: 'Tourism & Hospitality', icon: '🏨' },
  { id: 'pets-animals', name: 'Pets & Animals', icon: '🐾' },
  { id: 'wildlife-agriculture', name: 'Wildlife & Agriculture', icon: '🚜' },
  { id: 'daily-activities', name: 'Daily activities', icon: '🚵' },
  { id: 'emergency-services', name: 'Emergency Services', icon: '🚨' },
  { id: 'informal-services', name: 'Informal Services', icon: '🧹' },
];

// Menlyn Businesses - Urban Pretoria East focus
const MENLYN_BUSINESSES: Business[] = [
  {
    id: 'm1',
    name: 'The Capital Grill House',
    sectorId: 'food-drinks',
    subcategory: 'Fine Dining',
    description: 'Upscale steakhouse offering premium cuts, an extensive wine list, and sophisticated ambiance. Perfect for business dinners and special occasions.',
    phone: '+27 12 348 1234',
    email: 'reservations@capitalgrill.co.za',
    website: 'https://capitalgrill.co.za',
    address: 'Menlyn Park Shopping Centre, Pretoria',
    lat: -25.7823,
    lng: 28.2768,
    tier: 'premium',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm2',
    name: 'Garsfontein Motors',
    sectorId: 'automotive',
    subcategory: 'Car Dealership',
    description: 'Premium pre-owned vehicles with full service history. Finance available. Trade-ins welcome. Serving Pretoria East for over 15 years.',
    phone: '+27 12 993 5678',
    whatsapp: '+27 82 555 1234',
    email: 'sales@garsfonteinmotors.co.za',
    address: '234 Garsfontein Road, Garsfontein',
    lat: -25.7912,
    lng: 28.3015,
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm3',
    name: 'Faerie Glen Medical Centre',
    sectorId: 'health-wellness',
    subcategory: 'Medical Practice',
    description: 'Comprehensive medical centre with GPs, specialists, and diagnostic services. Same-day appointments available. Medical aid and private patients welcome.',
    phone: '+27 12 991 2345',
    email: 'reception@fgmedical.co.za',
    address: '45 Atterbury Road, Faerie Glen',
    lat: -25.7756,
    lng: 28.3102,
    tier: 'premium',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm4',
    name: 'Menlyn Fitness Hub',
    sectorId: 'health-wellness',
    subcategory: 'Gym & Fitness',
    description: '24-hour gym with state-of-the-art equipment, group classes, personal training, and wellness spa. First session free for new members.',
    phone: '+27 12 348 7890',
    whatsapp: '+27 73 444 5678',
    email: 'info@menlynfitness.co.za',
    website: 'https://menlynfitness.co.za',
    address: 'Menlyn Maine Central Square',
    lat: -25.7845,
    lng: 28.2789,
    tier: 'premium',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm5',
    name: 'Van Wyk & Associates Attorneys',
    sectorId: 'professional-services',
    subcategory: 'Legal Services',
    description: 'Full-service law firm specializing in commercial law, property transactions, and family law. Free initial consultation.',
    phone: '+27 12 460 1234',
    email: 'info@vwattorneys.co.za',
    address: 'Brooklyn Bridge Office Park, Pretoria',
    lat: -25.7678,
    lng: 28.2456,
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm6',
    name: 'Eastwood IT Solutions',
    sectorId: 'professional-services',
    subcategory: 'IT Services',
    description: 'Business IT support, cloud solutions, cybersecurity, and managed services. Serving SMEs across Pretoria East.',
    phone: '+27 12 993 8765',
    whatsapp: '+27 82 333 9876',
    email: 'support@eastwoodit.co.za',
    address: 'Lynnwood Bridge, Pretoria',
    lat: -25.7634,
    lng: 28.2812,
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm7',
    name: 'The Coffee Merchant',
    sectorId: 'food-drinks',
    subcategory: 'Coffee Shop',
    description: 'Artisan coffee roastery and cafe. Single-origin beans, specialty brews, and fresh pastries. Remote work friendly with fast WiFi.',
    phone: '+27 12 348 4567',
    whatsapp: '+27 76 222 3333',
    email: 'hello@coffeemerchant.co.za',
    address: 'Menlyn Maine, Pretoria',
    lat: -25.7841,
    lng: 28.2795,
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm8',
    name: 'Pretoria East Plumbing',
    sectorId: 'home-services',
    subcategory: 'Plumbing',
    description: '24/7 emergency plumbing services. Geyser repairs, leak detection, bathroom renovations. Licensed and insured.',
    phone: '+27 82 456 7890',
    whatsapp: '+27 82 456 7890',
    address: 'Serving Menlyn, Faerie Glen, Garsfontein',
    tier: 'micro',
    imageUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm9',
    name: 'Urban Paws Pet Spa',
    sectorId: 'pets-animals',
    subcategory: 'Pet Grooming',
    description: 'Professional pet grooming, daycare, and boarding. Specialized treatments for all breeds. Vetshop on premises.',
    phone: '+27 12 991 5555',
    whatsapp: '+27 73 111 2222',
    email: 'bookings@urbanpaws.co.za',
    address: '78 Lynnwood Road, Lynnwood',
    lat: -25.7589,
    lng: 28.2734,
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm10',
    name: 'Atterbury Accounting',
    sectorId: 'professional-services',
    subcategory: 'Accounting',
    description: 'Tax consulting, bookkeeping, payroll services, and business advisory. SAICA registered. Small business specialists.',
    phone: '+27 12 348 9012',
    email: 'accounts@atterburyacc.co.za',
    address: 'Atterbury House, Faerie Glen',
    lat: -25.7789,
    lng: 28.3056,
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm11',
    name: 'Silver Oaks Home Renovations',
    sectorId: 'construction-industrial',
    subcategory: 'Renovations',
    description: 'Complete home renovations, kitchen and bathroom remodels, painting, and tiling. Quality workmanship guaranteed.',
    phone: '+27 82 789 0123',
    whatsapp: '+27 82 789 0123',
    email: 'quotes@silveroaks.co.za',
    address: 'Serving all Pretoria East',
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm12',
    name: 'Bright Minds Learning Centre',
    sectorId: 'education-community',
    subcategory: 'Tutoring',
    description: 'Extra lessons for Grades 1-12. Maths, Science, English, and Afrikaans. Small groups and one-on-one available.',
    phone: '+27 12 993 3456',
    whatsapp: '+27 72 888 9999',
    email: 'enrol@brightminds.co.za',
    address: 'Garsfontein Shopping Centre',
    lat: -25.7934,
    lng: 28.3089,
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm13',
    name: 'Highveld Security Services',
    sectorId: 'emergency-services',
    subcategory: 'Security',
    description: 'Armed response, CCTV installation, electric fencing, and alarm systems. 24/7 control room. Residential and commercial.',
    phone: '+27 12 460 5678',
    email: 'info@highveldsecurity.co.za',
    address: 'Brooklyn, Pretoria',
    lat: -25.7712,
    lng: 28.2523,
    tier: 'premium',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm14',
    name: 'Sushi Fusion Menlyn',
    sectorId: 'food-drinks',
    subcategory: 'Japanese Restaurant',
    description: 'Contemporary Japanese cuisine with a South African twist. Fresh sushi, ramen, and teppanyaki. Delivery available.',
    phone: '+27 12 348 2222',
    whatsapp: '+27 73 555 6666',
    email: 'orders@sushifusion.co.za',
    address: 'Menlyn Park Shopping Centre',
    lat: -25.7825,
    lng: 28.2771,
    tier: 'standard',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm15',
    name: 'ProClean Domestic Services',
    sectorId: 'home-services',
    subcategory: 'Cleaning Services',
    description: 'Professional domestic cleaning, deep cleaning, and move-in/move-out services. Vetted and trained staff.',
    phone: '+27 82 111 3333',
    whatsapp: '+27 82 111 3333',
    address: 'Serving Pretoria East',
    tier: 'micro',
  },
  {
    id: 'm16',
    name: 'Menlyn Park Hotel & Spa',
    sectorId: 'tourism-hospitality',
    subcategory: 'Hotel',
    description: '4-star hotel in the heart of Menlyn. Conference facilities, spa, restaurant, and rooftop bar. Business and leisure.',
    phone: '+27 12 348 8888',
    email: 'reservations@menlynhotel.co.za',
    website: 'https://menlynparkhotel.co.za',
    address: 'Menlyn Maine, Pretoria',
    lat: -25.7838,
    lng: 28.2782,
    tier: 'hospitality',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm17',
    name: 'TechZone Electronics',
    sectorId: 'shopping-retail',
    subcategory: 'Electronics',
    description: 'Computers, smartphones, gaming, and accessories. Repairs and upgrades. Competitive prices and expert advice.',
    phone: '+27 12 993 7777',
    whatsapp: '+27 76 444 7777',
    email: 'sales@techzone.co.za',
    address: 'Woodlands Boulevard, Pretoria',
    lat: -25.7756,
    lng: 28.3201,
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'm18',
    name: 'Green Thumb Landscaping',
    sectorId: 'home-services',
    subcategory: 'Landscaping',
    description: 'Garden design, installation, and maintenance. Irrigation systems, instant lawn, and water features. Townhouse specialists.',
    phone: '+27 82 999 4444',
    whatsapp: '+27 82 999 4444',
    email: 'design@greenthumb.co.za',
    address: 'Serving all Pretoria East',
    tier: 'standard',
    imageUrl: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&q=80&w=800',
  },
];

// Menlyn Jobs - Corporate/Urban focus
const MENLYN_JOBS: Job[] = [
  {
    id: 'mj1',
    title: 'Software Developer',
    businessId: 'm6',
    businessName: 'Eastwood IT Solutions',
    jobType: 'full-time',
    sectorId: 'professional-services',
    description: 'Join our growing team developing enterprise solutions. Work with modern tech stack including React, Node.js, and cloud platforms.',
    requirements: ['3+ years development experience', 'JavaScript/TypeScript proficiency', 'Cloud experience (AWS/Azure)', 'Agile methodology', 'Degree in IT or related field'],
    salaryRange: 'R45,000 - R65,000 per month',
    location: 'Lynnwood Bridge, Pretoria',
    postedDate: '2025-01-12',
    applicationMethod: 'email',
    applicationContact: 'careers@eastwoodit.co.za',
    isActive: true,
  },
  {
    id: 'mj2',
    title: 'Restaurant Manager',
    businessId: 'm1',
    businessName: 'The Capital Grill House',
    jobType: 'full-time',
    sectorId: 'food-drinks',
    description: 'Lead our front-of-house team at this upscale dining establishment. Ensure exceptional guest experiences and operational excellence.',
    requirements: ['5+ years restaurant management', 'Fine dining experience preferred', 'Strong leadership skills', 'Wine knowledge advantageous', 'Flexible schedule including weekends'],
    salaryRange: 'R25,000 - R35,000 per month + incentives',
    location: 'Menlyn Park, Pretoria',
    postedDate: '2025-01-10',
    applicationMethod: 'email',
    applicationContact: 'hr@capitalgrill.co.za',
    isActive: true,
  },
  {
    id: 'mj3',
    title: 'Receptionist / Admin Assistant',
    businessId: 'm3',
    businessName: 'Faerie Glen Medical Centre',
    jobType: 'full-time',
    sectorId: 'health-wellness',
    description: 'Front desk position at busy medical practice. Handle patient bookings, billing, and general administration.',
    requirements: ['Matric certificate', 'Computer literate (MS Office)', 'Medical reception experience preferred', 'Professional demeanor', 'Bilingual (English/Afrikaans)'],
    salaryRange: 'R12,000 - R16,000 per month',
    location: 'Faerie Glen, Pretoria',
    postedDate: '2025-01-14',
    applicationMethod: 'email',
    applicationContact: 'hr@fgmedical.co.za',
    isActive: true,
  },
  {
    id: 'mj4',
    title: 'Sales Consultant - Vehicles',
    businessId: 'm2',
    businessName: 'Garsfontein Motors',
    jobType: 'full-time',
    sectorId: 'automotive',
    description: 'Sell quality pre-owned vehicles to walk-in and online customers. Basic salary plus excellent commission structure.',
    requirements: ['Valid drivers license', 'Sales experience', 'Customer service skills', 'Vehicle knowledge advantageous', 'Own transport'],
    salaryRange: 'R10,000 basic + commission (OTE R30,000+)',
    location: 'Garsfontein, Pretoria',
    postedDate: '2025-01-11',
    applicationMethod: 'whatsapp',
    applicationContact: '+27 82 555 1234',
    isActive: true,
  },
  {
    id: 'mj5',
    title: 'Personal Trainer',
    businessId: 'm4',
    businessName: 'Menlyn Fitness Hub',
    jobType: 'contract',
    sectorId: 'health-wellness',
    description: 'Certified personal trainer to work with diverse clientele. Build your own client base in a premium facility.',
    requirements: ['Recognized PT certification', 'First Aid certificate', 'Excellent communication', 'Passion for fitness', 'Professional appearance'],
    salaryRange: 'Commission-based (R20,000 - R40,000 earning potential)',
    location: 'Menlyn Maine, Pretoria',
    postedDate: '2025-01-13',
    applicationMethod: 'email',
    applicationContact: 'trainers@menlynfitness.co.za',
    isActive: true,
  },
  {
    id: 'mj6',
    title: 'Junior Accountant',
    businessId: 'm10',
    businessName: 'Atterbury Accounting',
    jobType: 'full-time',
    sectorId: 'professional-services',
    description: 'Entry-level position for recently qualified accountant. Exposure to diverse client base and mentorship opportunities.',
    requirements: ['BCom Accounting degree', 'SAICA articles advantageous', 'Pastel/Sage experience', 'Attention to detail', 'Valid drivers license'],
    salaryRange: 'R18,000 - R25,000 per month',
    location: 'Faerie Glen, Pretoria',
    postedDate: '2025-01-09',
    applicationMethod: 'email',
    applicationContact: 'careers@atterburyacc.co.za',
    isActive: true,
  },
  {
    id: 'mj7',
    title: 'Barista',
    businessId: 'm7',
    businessName: 'The Coffee Merchant',
    jobType: 'full-time',
    sectorId: 'food-drinks',
    description: 'Join our team of coffee enthusiasts. Training provided on specialty coffee preparation. Growth opportunities available.',
    requirements: ['Passion for coffee', 'Customer service skills', 'Ability to work in fast-paced environment', 'Flexible schedule', 'Barista experience a plus'],
    salaryRange: 'R8,000 - R12,000 per month + tips',
    location: 'Menlyn Maine, Pretoria',
    postedDate: '2025-01-15',
    applicationMethod: 'whatsapp',
    applicationContact: '+27 76 222 3333',
    isActive: true,
  },
  {
    id: 'mj8',
    title: 'Legal Secretary',
    businessId: 'm5',
    businessName: 'Van Wyk & Associates Attorneys',
    jobType: 'full-time',
    sectorId: 'professional-services',
    description: 'Support attorneys with legal administration, document preparation, and client liaison. Professional law firm environment.',
    requirements: ['Legal secretary diploma or experience', 'Excellent typing skills', 'Knowledge of legal terminology', 'Confidentiality', 'MS Office proficiency'],
    salaryRange: 'R15,000 - R22,000 per month',
    location: 'Brooklyn, Pretoria',
    postedDate: '2025-01-08',
    applicationMethod: 'email',
    applicationContact: 'hr@vwattorneys.co.za',
    isActive: true,
  },
  {
    id: 'mj9',
    title: 'Dog Groomer',
    businessId: 'm9',
    businessName: 'Urban Paws Pet Spa',
    jobType: 'full-time',
    sectorId: 'pets-animals',
    description: 'Experienced pet groomer for busy salon. All breeds. Friendly environment with modern equipment.',
    requirements: ['Pet grooming qualification or 2+ years experience', 'Love for animals', 'Physical fitness', 'Patience and gentle handling', 'Own transport preferred'],
    salaryRange: 'R10,000 - R15,000 per month',
    location: 'Lynnwood, Pretoria',
    postedDate: '2025-01-12',
    applicationMethod: 'whatsapp',
    applicationContact: '+27 73 111 2222',
    isActive: true,
  },
  {
    id: 'mj10',
    title: 'Hotel Front Desk Agent',
    businessId: 'm16',
    businessName: 'Menlyn Park Hotel & Spa',
    jobType: 'full-time',
    sectorId: 'tourism-hospitality',
    description: 'Guest services role at 4-star hotel. Check-ins, reservations, and guest relations. Shift work required.',
    requirements: ['Hospitality diploma or experience', 'Professional appearance', 'Computer literate', 'Fluent English', 'Customer service excellence'],
    salaryRange: 'R12,000 - R16,000 per month',
    location: 'Menlyn Maine, Pretoria',
    postedDate: '2025-01-14',
    applicationMethod: 'email',
    applicationContact: 'hr@menlynhotel.co.za',
    isActive: true,
  },
];

// Menlyn Events - Urban lifestyle focus
const MENLYN_EVENTS: Event[] = [
  {
    id: 'me1',
    title: 'Menlyn Maine Night Market',
    organizerId: null,
    organizerName: 'Menlyn Maine Management',
    eventType: 'market',
    description: 'Monthly night market featuring gourmet street food, craft beverages, artisan goods, and live music. Family-friendly atmosphere in the urban square.',
    date: '2025-02-07',
    startTime: '17:00',
    endTime: '22:00',
    location: 'Menlyn Maine Central Square',
    address: 'Menlyn Maine, Pretoria',
    ticketPrice: 'Free entry',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
  },
  {
    id: 'me2',
    title: 'Pretoria Business Networking Breakfast',
    organizerId: 'm5',
    organizerName: 'Pretoria Chamber of Commerce',
    eventType: 'other',
    description: 'Connect with Pretoria East business owners and professionals. Guest speaker on digital transformation. Continental breakfast included.',
    date: '2025-02-12',
    startTime: '07:00',
    endTime: '09:00',
    location: 'Menlyn Park Hotel',
    address: 'Menlyn Maine, Pretoria',
    ticketPrice: 'R250 per person',
    bookingLink: 'https://pretoriachamber.example.com/events',
    imageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'me3',
    title: 'Gin & Jazz Evening',
    organizerId: 'm16',
    organizerName: 'Menlyn Park Hotel & Spa',
    eventType: 'festival',
    description: 'Rooftop gin tasting with live jazz. Sample premium local and international gins paired with gourmet canapes. Sunset views over Pretoria.',
    date: '2025-02-14',
    startTime: '18:00',
    endTime: '22:00',
    location: 'Menlyn Park Hotel Rooftop',
    address: 'Menlyn Maine, Pretoria',
    ticketPrice: 'R350 per person',
    bookingLink: 'https://menlynhotel.example.com/events',
    imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
  },
  {
    id: 'me4',
    title: 'Pretoria Tech Meetup',
    organizerId: 'm6',
    organizerName: 'Pretoria Developer Community',
    eventType: 'workshop',
    description: 'Monthly tech meetup for developers, designers, and tech enthusiasts. Lightning talks, networking, and pizza. All skill levels welcome.',
    date: '2025-02-20',
    startTime: '18:00',
    endTime: '21:00',
    location: 'Eastwood IT Solutions',
    address: 'Lynnwood Bridge, Pretoria',
    ticketPrice: 'Free',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'me5',
    title: 'Wellness & Yoga Festival',
    organizerId: 'm4',
    organizerName: 'Menlyn Fitness Hub',
    eventType: 'festival',
    description: 'Day of wellness activities including yoga sessions, meditation workshops, healthy cooking demos, and wellness market. All fitness levels.',
    date: '2025-03-01',
    startTime: '08:00',
    endTime: '16:00',
    location: 'Menlyn Maine Park',
    address: 'Menlyn Maine, Pretoria',
    ticketPrice: 'R150 (includes yoga mat hire)',
    bookingLink: 'https://menlynfitness.example.com/wellness',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
  },
  {
    id: 'me6',
    title: 'Classic Car Show',
    organizerId: 'm2',
    organizerName: 'Pretoria Classic Car Club',
    eventType: 'community',
    description: 'Display of vintage and classic vehicles. Food trucks, live music, and family entertainment. Vehicle entries welcome.',
    date: '2025-02-23',
    startTime: '09:00',
    endTime: '15:00',
    location: 'Woodlands Boulevard Parking',
    address: 'Garsfontein Road, Pretoria',
    ticketPrice: 'R50 adults, kids free',
    imageUrl: 'https://images.unsplash.com/photo-1514316454349-750a7fd3da3a?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'me7',
    title: 'Kids Coding Workshop',
    organizerId: 'm12',
    organizerName: 'Bright Minds Learning Centre',
    eventType: 'workshop',
    description: 'Introduction to coding for kids aged 8-14. Learn Scratch programming and create your own games. Laptops provided.',
    date: '2025-02-15',
    startTime: '09:00',
    endTime: '12:00',
    location: 'Bright Minds Learning Centre',
    address: 'Garsfontein Shopping Centre',
    ticketPrice: 'R350 per child',
    bookingLink: 'https://brightminds.example.com/workshops',
    imageUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'me8',
    title: 'Artisan Food & Wine Fair',
    organizerId: null,
    organizerName: 'Pretoria Foodies Collective',
    eventType: 'festival',
    description: 'Celebrate local flavors with artisan food producers, boutique wineries, and craft breweries. Cooking demonstrations and tastings.',
    date: '2025-03-08',
    startTime: '10:00',
    endTime: '18:00',
    location: 'Brooklyn Square',
    address: 'Brooklyn, Pretoria',
    ticketPrice: 'R100 entry (includes tasting glass)',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
  },
  {
    id: 'me9',
    title: 'Property Investment Seminar',
    organizerId: null,
    organizerName: 'Pretoria Property Network',
    eventType: 'workshop',
    description: 'Learn about property investment in Pretoria East. Market trends, financing options, and expert panel discussion. Light refreshments.',
    date: '2025-02-26',
    startTime: '18:00',
    endTime: '20:30',
    location: 'Brooklyn Bridge Office Park',
    address: 'Fehrsen Street, Brooklyn',
    ticketPrice: 'R200 per person',
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'me10',
    title: 'Sunday Brunch Market',
    organizerId: null,
    organizerName: 'Lynnwood Community',
    eventType: 'market',
    description: 'Weekly Sunday market with fresh produce, baked goods, crafts, and ready-to-eat breakfast. Dog-friendly. Live acoustic music.',
    date: '2025-02-02',
    startTime: '08:00',
    endTime: '13:00',
    location: 'Lynnwood Lane',
    address: 'Lynnwood Road, Lynnwood',
    ticketPrice: 'Free entry',
    imageUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'me11',
    title: 'Startup Pitch Night',
    organizerId: null,
    organizerName: 'Pretoria Startup Hub',
    eventType: 'other',
    description: 'Watch local startups pitch to investors and industry experts. Network with entrepreneurs. Drinks and snacks included.',
    date: '2025-02-19',
    startTime: '17:30',
    endTime: '21:00',
    location: 'The Innovation Hub',
    address: 'Lynnwood Bridge, Pretoria',
    ticketPrice: 'R50 (free for startups)',
    imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'me12',
    title: 'Outdoor Movie Night',
    organizerId: null,
    organizerName: 'Menlyn Maine Entertainment',
    eventType: 'community',
    description: 'Watch a classic film under the stars. Bring your blankets and picnic baskets. Popcorn and drinks available for purchase.',
    date: '2025-02-28',
    startTime: '18:30',
    endTime: '22:00',
    location: 'Menlyn Maine Green',
    address: 'Menlyn Maine, Pretoria',
    ticketPrice: 'R80 per person',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
];

// Menlyn Classifieds - Urban items
const MENLYN_CLASSIFIEDS: Classified[] = [
  {
    id: 'mc1',
    title: 'MacBook Pro 16" M3 Max',
    category: 'for-sale',
    subcategory: 'Electronics',
    description: '2024 model, 64GB RAM, 1TB SSD. AppleCare+ until 2027. Includes original box and charger. Excellent condition.',
    price: 'R75,000',
    condition: 'used',
    sellerName: 'Michael',
    sellerContact: '+27 82 123 4567',
    location: 'Menlyn',
    postedDate: '2025-01-12',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'mc2',
    title: 'IKEA Sectional Sofa',
    category: 'for-sale',
    subcategory: 'Furniture',
    description: 'KIVIK sectional sofa in grey. L-shaped, seats 5. Removable washable covers. 2 years old, excellent condition. Relocating.',
    price: 'R12,000',
    condition: 'used',
    sellerName: 'Sandra',
    sellerContact: '+27 72 234 5678',
    location: 'Garsfontein',
    postedDate: '2025-01-14',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'mc3',
    title: 'Wanted: Parking Bay Menlyn Maine',
    category: 'wanted',
    subcategory: 'Parking',
    description: 'Looking to rent a covered parking bay in Menlyn Maine residential. Long-term lease preferred. Can pay monthly in advance.',
    condition: 'other',
    sellerName: 'David',
    sellerContact: '+27 83 345 6789',
    location: 'Menlyn Maine',
    postedDate: '2025-01-13',
    isActive: true,
  },
  {
    id: 'mc4',
    title: 'Interior Design Services',
    category: 'services',
    subcategory: 'Home Services',
    description: 'Qualified interior designer offering consultations, space planning, and full design services. Residential and small commercial. Portfolio available.',
    condition: 'other',
    sellerName: 'Studio Elara',
    sellerContact: '+27 76 456 7890',
    location: 'Pretoria East',
    postedDate: '2025-01-10',
    isActive: true,
  },
  {
    id: 'mc5',
    title: 'Golf Clubs - Titleist Set',
    category: 'for-sale',
    subcategory: 'Sports',
    description: 'Full Titleist set including driver, woods, irons, wedges, putter. Callaway bag included. Perfect for intermediate players.',
    price: 'R15,000',
    condition: 'used',
    sellerName: 'Johan',
    sellerContact: '+27 82 567 8901',
    location: 'Faerie Glen',
    postedDate: '2025-01-11',
    imageUrl: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'mc6',
    title: 'Private Maths Tutor',
    category: 'services',
    subcategory: 'Education',
    description: 'BSc Maths graduate offering private tutoring for Grades 10-12 and first-year university. Flexible hours. Your home or online.',
    condition: 'other',
    sellerName: 'Thabo',
    sellerContact: '+27 73 678 9012',
    location: 'Lynnwood',
    postedDate: '2025-01-09',
    isActive: true,
  },
  {
    id: 'mc7',
    title: 'Nespresso Vertuo Machine',
    category: 'for-sale',
    subcategory: 'Appliances',
    description: 'Nespresso Vertuo Plus with milk frother. Includes pod holder and 20 assorted capsules. 1 year old, barely used.',
    price: 'R2,500',
    condition: 'used',
    sellerName: 'Lisa',
    sellerContact: '+27 72 789 0123',
    location: 'Menlyn',
    postedDate: '2025-01-15',
    imageUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'mc8',
    title: 'Wanted: Office Chair',
    category: 'wanted',
    subcategory: 'Furniture',
    description: 'Looking for ergonomic office chair in good condition. Herman Miller or similar quality. Budget up to R8,000.',
    condition: 'other',
    sellerName: 'Mark',
    sellerContact: '+27 82 890 1234',
    location: 'Garsfontein',
    postedDate: '2025-01-14',
    isActive: true,
  },
  {
    id: 'mc9',
    title: 'iPhone 15 Pro Max 256GB',
    category: 'for-sale',
    subcategory: 'Electronics',
    description: 'Natural Titanium, excellent condition. Includes case, screen protector, and original charger. Still under warranty.',
    price: 'R22,000',
    condition: 'used',
    sellerName: 'Pieter',
    sellerContact: '+27 83 901 2345',
    location: 'Brooklyn',
    postedDate: '2025-01-13',
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'mc10',
    title: 'Moving Services',
    category: 'services',
    subcategory: 'Transport',
    description: 'Professional furniture removals in Pretoria. Experienced team, fully insured. Free quotes. Small and large moves.',
    condition: 'other',
    sellerName: 'Swift Movers',
    sellerContact: '+27 71 012 3456',
    location: 'Pretoria East',
    postedDate: '2025-01-08',
    isActive: true,
  },
  {
    id: 'mc11',
    title: 'Peloton Bike+',
    category: 'for-sale',
    subcategory: 'Fitness',
    description: 'Peloton Bike+ with rotating screen. Includes mat, weights, and heart rate monitor. Subscription transferable. Moving overseas.',
    price: 'R45,000',
    condition: 'used',
    sellerName: 'Emma',
    sellerContact: '+27 82 234 5678',
    location: 'Faerie Glen',
    postedDate: '2025-01-12',
    imageUrl: 'https://images.unsplash.com/photo-1591291621164-2c6367723315?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'mc12',
    title: 'Free: Moving Boxes',
    category: 'other',
    subcategory: 'Free Stuff',
    description: 'About 30 good quality moving boxes, various sizes. Some bubble wrap included. You collect from Lynnwood.',
    condition: 'other',
    sellerName: 'Refiloe',
    sellerContact: '+27 76 345 6789',
    location: 'Lynnwood',
    postedDate: '2025-01-15',
    isActive: true,
  },
  {
    id: 'mc13',
    title: 'Dyson V15 Vacuum',
    category: 'for-sale',
    subcategory: 'Appliances',
    description: 'Dyson V15 Detect cordless vacuum. All attachments included. 6 months old, receipt available.',
    price: 'R9,500',
    condition: 'used',
    sellerName: 'Nicole',
    sellerContact: '+27 72 456 7890',
    location: 'Menlyn',
    postedDate: '2025-01-11',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'mc14',
    title: 'Web Development Services',
    category: 'services',
    subcategory: 'IT Services',
    description: 'Freelance web developer. WordPress, Shopify, custom React sites. SEO optimization included. Portfolio available on request.',
    condition: 'other',
    sellerName: 'CodeCraft Studio',
    sellerContact: '+27 82 567 8901',
    location: 'Pretoria East',
    postedDate: '2025-01-10',
    isActive: true,
  },
  {
    id: 'mc15',
    title: 'BMW 3 Series 320i 2020',
    category: 'for-sale',
    subcategory: 'Vehicles',
    description: 'F30 320i M Sport, white. 48,000km, full service history at BMW. Excellent condition. Private sale, no dealers.',
    price: 'R520,000',
    condition: 'used',
    sellerName: 'Andre',
    sellerContact: '+27 82 678 9012',
    location: 'Garsfontein',
    postedDate: '2025-01-09',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
];

// Menlyn Properties - Urban residential
const MENLYN_PROPERTIES: Property[] = [
  {
    id: 'mp1',
    title: 'Modern Penthouse Apartment',
    listingType: 'sale',
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 2,
    size: 180,
    price: 'R4,200,000',
    description: 'Stunning top-floor penthouse in secure complex. Open-plan living, gourmet kitchen, private rooftop terrace with Jacuzzi. 24-hour security, 2 parkings.',
    address: 'Menlyn Maine Residences',
    lat: -25.7835,
    lng: 28.2775,
    features: ['Rooftop terrace', 'Jacuzzi', '24-hour security', 'Gym access', '2 parking bays', 'Fiber ready'],
    agentName: 'Pam Golding Menlyn',
    agentContact: '+27 12 348 1111',
    postedDate: '2025-01-08',
    imageUrls: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: true,
  },
  {
    id: 'mp2',
    title: 'Family Home in Faerie Glen',
    listingType: 'sale',
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 3,
    size: 320,
    price: 'R3,850,000',
    description: 'Spacious family home on 1,200sqm stand. Open-plan living, study, double garage, pool. Established garden with borehole. Walking distance to Faerie Glen shops.',
    address: 'Atterbury Road, Faerie Glen',
    lat: -25.7768,
    lng: 28.3078,
    features: ['Swimming pool', 'Double garage', 'Study/home office', 'Borehole', 'Alarm system', 'Electric fence'],
    agentName: 'Seeff Pretoria East',
    agentContact: '+27 12 991 2222',
    postedDate: '2025-01-10',
    imageUrls: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: true,
  },
  {
    id: 'mp3',
    title: 'Luxury Apartment to Rent',
    listingType: 'rent',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    size: 95,
    price: 'R18,500 per month',
    description: 'Fully furnished luxury apartment in Menlyn Maine. Modern finishes, balcony with city views. Gym, pool, and concierge included.',
    address: 'Menlyn Maine, Pretoria',
    lat: -25.7842,
    lng: 28.2788,
    features: ['Fully furnished', 'Balcony', 'Gym access', 'Pool', 'Concierge', 'Secure parking'],
    agentName: 'Rawson Menlyn',
    agentContact: '+27 12 348 3333',
    postedDate: '2025-01-12',
    imageUrls: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'mp4',
    title: 'Modern Townhouse Complex',
    listingType: 'sale',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 2,
    size: 165,
    price: 'R2,650,000',
    description: 'Brand new 3-bed townhouse in secure estate. Double-volume living area, private garden, double garage. Low levies. 10 mins to Menlyn.',
    address: 'Garsfontein Secure Estate',
    lat: -25.7925,
    lng: 28.3045,
    features: ['Brand new', 'Double garage', 'Private garden', 'Low levies', 'Fiber installed', '24-hour security'],
    agentName: 'RE/MAX Pretoria East',
    agentContact: '+27 12 993 4444',
    postedDate: '2025-01-06',
    imageUrls: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'mp5',
    title: 'Commercial Space - Brooklyn',
    listingType: 'rent',
    propertyType: 'commercial',
    size: 200,
    price: 'R35,000 per month',
    description: 'Prime retail/office space on Fehrsen Street. High foot traffic, ample parking. Suitable for professional services or boutique retail.',
    address: 'Brooklyn Bridge, Pretoria',
    lat: -25.7698,
    lng: 28.2501,
    features: ['Street frontage', 'Ample parking', 'Air conditioning', '3-phase power', 'Fiber ready', 'Alarm system'],
    agentName: 'JHI Properties',
    agentContact: '+27 12 460 5555',
    postedDate: '2025-01-09',
    imageUrls: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'mp6',
    title: 'Bachelor Flat Lynnwood',
    listingType: 'rent',
    propertyType: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    size: 40,
    price: 'R7,500 per month',
    description: 'Cozy bachelor flat in quiet complex. Open-plan with kitchenette. Secure parking. Water included. Close to Tuks and shops.',
    address: 'Lynnwood Glen, Pretoria',
    lat: -25.7612,
    lng: 28.2789,
    features: ['Water included', 'Secure parking', 'Prepaid electricity', 'Close to Tuks', 'Pet-friendly'],
    agentName: 'Direct from Owner',
    agentContact: '+27 82 666 7777',
    postedDate: '2025-01-14',
    imageUrls: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'mp7',
    title: 'Executive Home Waterkloof Ridge',
    listingType: 'sale',
    propertyType: 'house',
    bedrooms: 5,
    bathrooms: 4,
    size: 480,
    price: 'R8,500,000',
    description: 'Prestigious address with panoramic city views. Entertainment areas, home cinema, wine cellar. Staff quarters. Triple garage.',
    address: 'Waterkloof Ridge, Pretoria',
    lat: -25.7856,
    lng: 28.2312,
    features: ['City views', 'Home cinema', 'Wine cellar', 'Staff quarters', 'Triple garage', 'Swimming pool'],
    agentName: 'Sothebys International',
    agentContact: '+27 12 460 8888',
    postedDate: '2025-01-05',
    imageUrls: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: true,
  },
  {
    id: 'mp8',
    title: 'Investment Apartment',
    listingType: 'sale',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    size: 72,
    price: 'R1,150,000',
    description: 'Excellent investment opportunity in Arcadia. Currently tenanted at R9,500/month. Secure complex with pool. Low levies.',
    address: 'Arcadia, Pretoria',
    lat: -25.7534,
    lng: 28.2234,
    features: ['Currently tenanted', 'Secure complex', 'Swimming pool', 'Low levies', 'Close to CBD'],
    agentName: 'Property Point',
    agentContact: '+27 12 342 9999',
    postedDate: '2025-01-11',
    imageUrls: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'mp9',
    title: 'Office Space Lynnwood Bridge',
    listingType: 'rent',
    propertyType: 'commercial',
    size: 85,
    price: 'R15,000 per month',
    description: 'Modern office in prestigious Lynnwood Bridge complex. Includes 2 parkings. Building has gym, restaurant, and 24-hour security.',
    address: 'Lynnwood Bridge, Pretoria',
    lat: -25.7645,
    lng: 28.2823,
    features: ['2 parking bays', 'Building gym', 'Restaurant on-site', '24-hour security', 'Fiber internet', 'Air conditioning'],
    agentName: 'Broll Property',
    agentContact: '+27 12 361 0000',
    postedDate: '2025-01-13',
    imageUrls: [
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'mp10',
    title: 'Vacant Stand - Garsfontein',
    listingType: 'sale',
    propertyType: 'land',
    size: 800,
    price: 'R1,800,000',
    description: '800sqm residential stand in established area. Building plans available. Close to schools and shopping centers.',
    address: 'Garsfontein, Pretoria',
    lat: -25.7945,
    lng: 28.3067,
    features: ['Plans available', 'Flat terrain', 'Municipal services', 'Close to schools', 'Quiet street'],
    agentName: 'Harcourts Pretoria',
    agentContact: '+27 12 993 1111',
    postedDate: '2025-01-07',
    imageUrls: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
];

// Menlyn Announcements - Urban community
const MENLYN_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ma1',
    title: 'Load Shedding Schedule Change',
    category: 'alert',
    description: 'Pretoria East has been moved to Group 5 for load shedding. Please update your schedules. Check CityPower app for real-time updates.',
    contactName: 'City of Tshwane',
    contactMethod: '0860 111 556',
    location: 'Pretoria East',
    postedDate: '2025-01-15',
    expiryDate: '2025-12-31',
    isActive: true,
  },
  {
    id: 'ma2',
    title: 'LOST: Golden Retriever',
    category: 'lost-found',
    description: 'Male Golden Retriever "Max" missing from Faerie Glen since Sunday afternoon. Wearing blue collar with tag. Reward R2,000 for safe return.',
    contactName: 'Van der Berg Family',
    contactMethod: '+27 82 111 2222',
    location: 'Faerie Glen',
    postedDate: '2025-01-14',
    expiryDate: '2025-01-28',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'ma3',
    title: 'Menlyn Maine Road Works',
    category: 'alert',
    description: 'Corobay Avenue will have lane closures from 22-26 January for maintenance. Expect delays during peak hours. Use alternative routes via Atterbury.',
    contactName: 'Menlyn Maine Management',
    contactMethod: '+27 12 348 0000',
    location: 'Menlyn Maine',
    postedDate: '2025-01-12',
    expiryDate: '2025-01-27',
    isActive: true,
  },
  {
    id: 'ma4',
    title: 'Neighbourhood Watch Meeting',
    category: 'community-notice',
    description: 'Monthly Garsfontein neighbourhood watch meeting at NG Kerk hall. Topics: recent break-ins, patrol roster, new security initiatives.',
    contactName: 'Garsfontein CPF',
    contactMethod: '+27 72 333 4444',
    location: 'NG Kerk Garsfontein',
    postedDate: '2025-01-13',
    expiryDate: '2025-01-20',
    isActive: true,
  },
  {
    id: 'ma5',
    title: 'FOUND: Set of Car Keys',
    category: 'lost-found',
    description: 'VW car keys with remote found in Menlyn Park parking level 3 on Tuesday. Contact security desk to claim with description.',
    contactName: 'Menlyn Park Security',
    contactMethod: '+27 12 348 5000',
    location: 'Menlyn Park Shopping Centre',
    postedDate: '2025-01-14',
    expiryDate: '2025-02-14',
    isActive: true,
  },
  {
    id: 'ma6',
    title: 'Water Maintenance Notice',
    category: 'alert',
    description: 'Scheduled water maintenance in Lynnwood area on 25 January from 08:00-16:00. Please store water. Apologies for inconvenience.',
    contactName: 'Rand Water',
    contactMethod: '0860 10 10 60',
    location: 'Lynnwood, Pretoria',
    postedDate: '2025-01-10',
    expiryDate: '2025-01-26',
    isActive: true,
  },
  {
    id: 'ma7',
    title: 'Free Vaccination Drive',
    category: 'community-notice',
    description: 'Department of Health offering free flu vaccinations at Garsfontein Clinic. No appointment needed. Bring ID. Available while stocks last.',
    contactName: 'Gauteng Health',
    contactMethod: '0800 029 999',
    location: 'Garsfontein Clinic',
    postedDate: '2025-01-11',
    expiryDate: '2025-01-31',
    isActive: true,
  },
  {
    id: 'ma8',
    title: 'Fiber Installation Notice',
    category: 'community-notice',
    description: 'Openserve will be installing fiber in Faerie Glen Ext 2 during February. Temporary road closures may occur. Free installation for residents.',
    contactName: 'Openserve',
    contactMethod: '0800 022 022',
    location: 'Faerie Glen',
    postedDate: '2025-01-15',
    expiryDate: '2025-02-28',
    isActive: true,
  },
];

// Menlyn Specials - Urban lifestyle focus
const MENLYN_SPECIALS: Special[] = [
  {
    id: 'ms1',
    businessId: 'm1',
    businessName: 'The Capital Grill House',
    title: 'Executive Lunch Special',
    offer: '3-Course Lunch for R295',
    validUntil: 'Weekdays Only',
    description: 'Business lunch special including starter, main course, and dessert. Perfect for client meetings. Includes complimentary still or sparkling water.',
    icon: '🥩',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'ms2',
    businessId: 'm4',
    businessName: 'Menlyn Fitness Hub',
    title: 'New Year Fitness Package',
    offer: '3 Months for the Price of 2',
    validUntil: '28 February 2025',
    description: 'Kickstart your fitness journey with our new year special. Includes unlimited gym access, 2 PT sessions, and body composition analysis.',
    icon: '💪',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'ms3',
    businessId: 'm16',
    businessName: 'Menlyn Park Hotel & Spa',
    title: 'Staycation Weekend Package',
    offer: 'R1,999 per Night Including Breakfast',
    validUntil: 'Book by March 2025',
    description: 'Escape the city without leaving it. Includes luxury room, breakfast for two, spa voucher, and late checkout. Perfect urban getaway.',
    icon: '🏨',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800'
  }
];

// Menlyn Configuration
export const menlynConfig: TownConfig = {
  id: 'menlyn',
  slug: 'menlyn',

  town: {
    name: 'Menlyn',
    tagline: 'Pretoria East Business Hub',
    region: 'Gauteng',
  },

  branding: {
    colors: {
      primary: '#1e3a5f',    // Deep navy blue
      secondary: '#c9a227',   // Gold
      accent: '#f5f5f5',      // Light gray
    },
    heroImage: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&q=80&w=1920',
    faviconEmoji: 'M',
  },

  contact: {
    whatsapp: '27123456789', // Update with actual number
    email: 'hello@menlynconnect.co.za',
    phone: '012 345 6789',
  },

  location: {
    center: { lat: -25.7823, lng: 28.2768 }, // Menlyn, Pretoria
    zoom: 13,
  },

  // Slightly higher pricing for urban market
  pricing: {
    micro: { monthly: 'R75', annual: 'R750' },
    standard: { monthly: 'R249', annual: 'R2,739' },
    premium: { monthly: 'R449', annual: 'R4,939' },
    enterprise: { monthly: 'R799', annual: 'R8,789' },
  },

  data: {
    sectors: MENLYN_SECTORS,
    businesses: MENLYN_BUSINESSES,
    jobs: MENLYN_JOBS,
    events: MENLYN_EVENTS,
    classifieds: MENLYN_CLASSIFIEDS,
    properties: MENLYN_PROPERTIES,
    announcements: MENLYN_ANNOUNCEMENTS,
    specials: MENLYN_SPECIALS,
  },
};
