import { Business, Sector, Job, Event, Classified, Property, Announcement } from './types';

export const SECTORS: Sector[] = [
  { id: 'home-services', name: 'Home Services', icon: '🏠' },
  { id: 'automotive', name: 'Automotive', icon: '🚗' },
  { id: 'health-wellness', name: 'Health & Wellness', icon: '🌿' },
  { id: 'food-drinks', name: 'Food & Drinks', icon: '🍴' },
  { id: 'shopping-retail', name: 'Shopping & Retail', icon: '🛍️' },
  { id: 'professional-services', name: 'Professional Services', icon: '⚖️' },
  { id: 'construction-industrial', name: 'Construction & Industrial', icon: '🏗️' },
  { id: 'education-community', name: 'Education & Community', icon: '🎓' },
  { id: 'tourism-hospitality', name: 'Tourism & Hospitality', icon: '🏨' },
  { id: 'pets-animals', name: 'Pets & Animals', icon: '🐾' },
  { id: 'wildlife-agriculture', name: 'Wildlife & Agriculture', icon: '🚜' },
  { id: 'daily-activities', name: 'Daily activities', icon: '🚵' },
  { id: 'emergency-services', name: 'Emergency Services', icon: '🚨' },
  { id: 'informal-services', name: 'Informal Services', icon: '🧹' },
];

export const BUSINESSES: Business[] = [
  {
    id: '1',
    name: 'Test Business Vaalwater',
    sectorId: 'food-drinks',
    subcategory: 'Cafe',
    description: 'Test listing for Vaalwater Connect',
    phone: '+27 14 755 1234',
    email: 'test@example.com',
    address: 'Main Road, Vaalwater',
    tier: 'standard',
  }
];

export const JOBS: Job[] = [
  {
    id: 'job1',
    title: 'Game Lodge Manager',
    businessId: '1',
    businessName: 'Waterberg Safari Lodge',
    jobType: 'full-time',
    sectorId: 'tourism-hospitality',
    description: 'We are seeking an experienced Lodge Manager to oversee daily operations at our 5-star game lodge. The ideal candidate will have a passion for hospitality and wildlife conservation.',
    requirements: ['5+ years lodge management experience', 'Strong leadership skills', 'Knowledge of game reserve operations', 'Excellent guest relations', 'Valid drivers license'],
    salaryRange: 'R35,000 - R45,000 per month',
    location: 'Vaalwater',
    postedDate: '2025-01-10',
    applicationMethod: 'email',
    applicationContact: 'careers@waterbergsafari.co.za',
    isActive: true,
  },
  {
    id: 'job2',
    title: 'Farm Worker',
    businessId: '1',
    businessName: 'Grootfontein Farms',
    jobType: 'full-time',
    sectorId: 'wildlife-agriculture',
    description: 'Seeking reliable farm worker for cattle and crop farming operations. Accommodation provided on site.',
    requirements: ['Experience with livestock handling', 'Tractor driving ability', 'Physical fitness', 'Reliable and hardworking'],
    salaryRange: 'R6,500 - R8,000 per month + accommodation',
    location: 'Vaalwater District',
    postedDate: '2025-01-12',
    applicationMethod: 'phone',
    applicationContact: '+27 82 555 1234',
    isActive: true,
  },
  {
    id: 'job3',
    title: 'Chef / Cook',
    businessId: '1',
    businessName: 'The Stoep Cafe',
    jobType: 'full-time',
    sectorId: 'food-drinks',
    description: 'Looking for a talented chef to join our team. Must be able to prepare breakfast, lunch and light dinners with a focus on local ingredients.',
    requirements: ['Culinary qualification or 3+ years experience', 'Knowledge of South African cuisine', 'Food hygiene certificate', 'Team player'],
    salaryRange: 'R12,000 - R18,000 per month',
    location: 'Vaalwater',
    postedDate: '2025-01-08',
    applicationMethod: 'whatsapp',
    applicationContact: '+27 72 333 4567',
    isActive: true,
  },
  {
    id: 'job4',
    title: 'Domestic Worker',
    businessId: '1',
    businessName: 'Private Household',
    jobType: 'part-time',
    sectorId: 'home-services',
    description: 'Part-time domestic worker needed for cleaning and laundry. 3 days per week (Mon, Wed, Fri).',
    requirements: ['Experience in domestic work', 'Honest and reliable', 'References required'],
    salaryRange: 'R350 per day',
    location: 'Vaalwater',
    postedDate: '2025-01-14',
    applicationMethod: 'whatsapp',
    applicationContact: '+27 83 444 5678',
    isActive: true,
  },
  {
    id: 'job5',
    title: 'Receptionist',
    businessId: '1',
    businessName: 'Waterberg Medical Centre',
    jobType: 'full-time',
    sectorId: 'health-wellness',
    description: 'Front desk receptionist needed for busy medical practice. Must be friendly, organized and able to handle patient bookings.',
    requirements: ['Matric certificate', 'Computer literate', 'Good communication skills', 'Medical reception experience preferred'],
    salaryRange: 'R9,000 - R12,000 per month',
    location: 'Vaalwater',
    postedDate: '2025-01-11',
    applicationMethod: 'email',
    applicationContact: 'admin@waterbergmedical.co.za',
    isActive: true,
  },
  {
    id: 'job6',
    title: 'Safari Guide',
    businessId: '1',
    businessName: 'Bushveld Adventures',
    jobType: 'contract',
    sectorId: 'tourism-hospitality',
    description: 'Experienced safari guide needed for the peak season. FGASA qualification required.',
    requirements: ['FGASA Level 1 minimum', 'Valid PDP', 'First Aid certificate', 'Excellent knowledge of local flora and fauna', 'Passion for conservation'],
    salaryRange: 'R15,000 - R22,000 per month',
    location: 'Waterberg Biosphere',
    postedDate: '2025-01-09',
    applicationMethod: 'email',
    applicationContact: 'guides@bushveldadventures.co.za',
    isActive: true,
  },
  {
    id: 'job7',
    title: 'Mechanic Assistant',
    businessId: '1',
    businessName: 'Vaalwater Motors',
    jobType: 'full-time',
    sectorId: 'automotive',
    description: 'Looking for a mechanic assistant to help with vehicle servicing and repairs. Training provided for the right candidate.',
    requirements: ['Basic mechanical knowledge', 'Willingness to learn', 'Physically fit', 'Drivers license advantageous'],
    salaryRange: 'R7,000 - R9,000 per month',
    location: 'Vaalwater',
    postedDate: '2025-01-13',
    applicationMethod: 'phone',
    applicationContact: '+27 14 755 1234',
    isActive: true,
  },
  {
    id: 'job8',
    title: 'Gardener',
    businessId: '1',
    businessName: 'Multiple Households',
    jobType: 'casual',
    sectorId: 'home-services',
    description: 'Experienced gardener wanted for regular garden maintenance work across multiple properties in Vaalwater area.',
    requirements: ['Garden maintenance experience', 'Own transport preferred', 'Knowledge of indigenous plants', 'Reliable'],
    salaryRange: 'R250 - R300 per day',
    location: 'Vaalwater',
    postedDate: '2025-01-15',
    applicationMethod: 'whatsapp',
    applicationContact: '+27 76 222 3333',
    isActive: true,
  },
  {
    id: 'job9',
    title: 'Shop Assistant',
    businessId: '1',
    businessName: 'Vaalwater Spar',
    jobType: 'full-time',
    sectorId: 'shopping-retail',
    description: 'Friendly shop assistant needed for our grocery store. Must be able to work weekends and public holidays.',
    requirements: ['Matric certificate', 'Customer service skills', 'Cash handling experience', 'Willing to work shifts'],
    salaryRange: 'R5,500 - R7,000 per month',
    location: 'Vaalwater',
    postedDate: '2025-01-07',
    applicationMethod: 'email',
    applicationContact: 'hr@vaalwaterspar.co.za',
    isActive: true,
  },
  {
    id: 'job10',
    title: 'Bookkeeper',
    businessId: '1',
    businessName: 'Van der Merwe Attorneys',
    jobType: 'part-time',
    sectorId: 'professional-services',
    description: 'Part-time bookkeeper needed for small law firm. 3 days per week. Pastel experience essential.',
    requirements: ['Bookkeeping qualification', 'Pastel Accounting proficiency', '3+ years experience', 'Attention to detail'],
    salaryRange: 'R8,000 - R10,000 per month (part-time)',
    location: 'Vaalwater',
    postedDate: '2025-01-06',
    applicationMethod: 'email',
    applicationContact: 'admin@vdmattorneys.co.za',
    isActive: true,
  },
];

export const EVENTS: Event[] = [
  {
    id: 'evt1',
    title: 'Vaalwater Farmers Market',
    organizerId: null,
    organizerName: 'Vaalwater Community',
    eventType: 'market',
    description: 'Monthly farmers market featuring fresh produce, artisan goods, home-baked treats, and local crafts. Live music and food stalls. Family-friendly event.',
    date: '2025-02-01',
    startTime: '08:00',
    endTime: '13:00',
    location: 'Vaalwater Community Hall',
    address: 'Main Road, Vaalwater',
    ticketPrice: 'Free entry',
    imageUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
  },
  {
    id: 'evt2',
    title: 'Waterberg Wine & Cheese Festival',
    organizerId: '1',
    organizerName: 'Waterberg Tourism Association',
    eventType: 'festival',
    description: 'Annual celebration of fine wines and artisan cheeses from the region. Featuring local vineyards, cheese makers, and gourmet food vendors. Live entertainment throughout the day.',
    date: '2025-02-15',
    startTime: '10:00',
    endTime: '18:00',
    location: 'Zeederberg Wine Estate',
    address: 'R33, Waterberg',
    ticketPrice: 'R150 per person (includes wine glass)',
    bookingLink: 'https://tickets.example.com/wine-cheese',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
  },
  {
    id: 'evt3',
    title: 'Bush Photography Workshop',
    organizerId: '1',
    organizerName: 'Safari Photo Academy',
    eventType: 'workshop',
    description: 'Learn wildlife photography from professional photographers. Full day workshop includes game drive, theory session, and hands-on practice. Suitable for beginners to intermediate.',
    date: '2025-02-08',
    startTime: '05:30',
    endTime: '17:00',
    location: 'Marakele National Park',
    address: 'Marakele National Park, Waterberg',
    ticketPrice: 'R2,500 per person',
    bookingLink: 'https://safariph oto.example.com/book',
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'evt4',
    title: 'Community Clean-Up Day',
    organizerId: null,
    organizerName: 'Vaalwater Cleanup Committee',
    eventType: 'community',
    description: 'Join us for our quarterly town cleanup. Gloves and bags provided. Refreshments after. Let us keep Vaalwater beautiful!',
    date: '2025-01-25',
    startTime: '07:00',
    endTime: '11:00',
    location: 'Vaalwater Town Centre',
    address: 'Meet at the library, Main Road',
    ticketPrice: 'Free',
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'evt5',
    title: 'Stargazing Evening',
    organizerId: '1',
    organizerName: 'Waterberg Astronomical Society',
    eventType: 'other',
    description: 'Experience the pristine night skies of the Waterberg. Telescopes provided, expert guidance on constellations and planets. Hot chocolate included.',
    date: '2025-02-22',
    startTime: '19:00',
    endTime: '22:00',
    location: 'Horizon Lodge Observatory',
    address: 'R517, Vaalwater',
    ticketPrice: 'R100 per person, R50 children',
    imageUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
  },
  {
    id: 'evt6',
    title: 'Kids Holiday Camp',
    organizerId: '1',
    organizerName: 'Bushveld Adventures',
    eventType: 'workshop',
    description: 'Week-long adventure camp for children aged 8-14. Activities include hiking, nature studies, crafts, and outdoor survival skills. Day camp option available.',
    date: '2025-03-17',
    startTime: '08:00',
    endTime: '16:00',
    location: 'Bushveld Adventures Camp',
    address: 'Farm Rooiberg, Vaalwater',
    ticketPrice: 'R3,500 per week / R800 per day',
    bookingLink: 'https://bushveldcamp.example.com',
    imageUrl: 'https://images.unsplash.com/photo-1472745942893-4b9f730c7668?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'evt7',
    title: 'Valentine Dinner at the Lodge',
    organizerId: '1',
    organizerName: 'Sunset Ridge Lodge',
    eventType: 'other',
    description: 'Romantic 5-course dinner under the stars. Live jazz music, premium wines included. Limited to 20 couples for an intimate experience.',
    date: '2025-02-14',
    startTime: '18:30',
    endTime: '23:00',
    location: 'Sunset Ridge Lodge',
    address: 'R510, Waterberg',
    ticketPrice: 'R1,800 per couple',
    bookingLink: 'https://sunsetridge.example.com/valentines',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
  },
  {
    id: 'evt8',
    title: 'Mountain Bike Trail Run',
    organizerId: null,
    organizerName: 'Waterberg MTB Club',
    eventType: 'community',
    description: 'Annual mountain bike event with 25km and 50km routes through scenic bushveld. Registration includes race number, water stations, and medal.',
    date: '2025-03-08',
    startTime: '06:00',
    endTime: '12:00',
    location: 'Entabeni Game Reserve',
    address: 'Entabeni entrance, R518',
    ticketPrice: 'R250 (25km) / R350 (50km)',
    bookingLink: 'https://waterbergmtb.example.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'evt9',
    title: 'Craft Beer Tasting',
    organizerId: '1',
    organizerName: 'Waterberg Brewing Co',
    eventType: 'festival',
    description: 'Sample our new seasonal brews paired with local cheeses and biltong. Brewery tour included. Take-home tasting glasses.',
    date: '2025-02-28',
    startTime: '14:00',
    endTime: '18:00',
    location: 'Waterberg Brewing Co',
    address: 'Industrial Road, Vaalwater',
    ticketPrice: 'R180 per person',
    imageUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'evt10',
    title: 'First Aid Training Course',
    organizerId: '1',
    organizerName: 'Red Cross Limpopo',
    eventType: 'workshop',
    description: 'Level 1 First Aid certification course. Essential training for farm workers, guides, and anyone in remote areas. Certificate valid for 3 years.',
    date: '2025-02-05',
    startTime: '08:00',
    endTime: '17:00',
    location: 'Vaalwater Community Hall',
    address: 'Main Road, Vaalwater',
    ticketPrice: 'R850 per person',
    bookingLink: 'https://redcross.example.com/limpopo',
    imageUrl: 'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'evt11',
    title: 'Art in the Bush Exhibition',
    organizerId: null,
    organizerName: 'Waterberg Art Collective',
    eventType: 'other',
    description: 'Outdoor art exhibition showcasing local artists. Sculptures, paintings, and installations set against the natural bushveld backdrop. Art for sale.',
    date: '2025-03-22',
    startTime: '10:00',
    endTime: '16:00',
    location: 'Mabula Private Game Reserve',
    address: 'Mabula, R516',
    ticketPrice: 'R80 entry',
    imageUrl: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
  {
    id: 'evt12',
    title: 'Sunday Lunch Jazz',
    organizerId: '1',
    organizerName: 'The Stoep Cafe',
    eventType: 'other',
    description: 'Relaxed Sunday lunch with live jazz from 12pm. Buffet lunch and drinks available. Booking essential.',
    date: '2025-02-09',
    startTime: '12:00',
    endTime: '16:00',
    location: 'The Stoep Cafe',
    address: 'Main Road, Vaalwater',
    ticketPrice: 'A la carte menu',
    imageUrl: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
  },
];

export const CLASSIFIEDS: Classified[] = [
  {
    id: 'cls1',
    title: 'Toyota Hilux 2.4 GD-6 4x4',
    category: 'for-sale',
    subcategory: 'Vehicles',
    description: '2019 model, 85,000km. Service history, one owner. Canopy included. Excellent condition, ideal for farm use.',
    price: 'R385,000',
    condition: 'used',
    sellerName: 'Johan',
    sellerContact: '+27 82 111 2222',
    location: 'Vaalwater',
    postedDate: '2025-01-10',
    imageUrl: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'cls2',
    title: 'Game Fencing - 2.4m High',
    category: 'for-sale',
    subcategory: 'Farm Equipment',
    description: '500 meters of game fencing available. Includes droppers and stays. Excellent condition, removed from farm conversion.',
    price: 'R45 per meter',
    condition: 'used',
    sellerName: 'Pieter',
    sellerContact: '+27 83 333 4444',
    location: 'Modimolle',
    postedDate: '2025-01-12',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'cls3',
    title: 'Wanted: Accommodation for 2 farm workers',
    category: 'wanted',
    subcategory: 'Accommodation',
    description: 'Looking for accommodation for 2 reliable farm workers. Can be wendy house, room, or small cottage. Vaalwater area.',
    condition: 'other',
    sellerName: 'Sarah',
    sellerContact: '+27 72 555 6666',
    location: 'Vaalwater',
    postedDate: '2025-01-14',
    isActive: true,
  },
  {
    id: 'cls4',
    title: 'Plumbing Services',
    category: 'services',
    subcategory: 'Home Services',
    description: 'Experienced plumber available for repairs, installations, and maintenance. Geysers, burst pipes, blocked drains. Free quotes.',
    condition: 'other',
    sellerName: 'Willem Plumbing',
    sellerContact: '+27 76 777 8888',
    location: 'Vaalwater & surrounds',
    postedDate: '2025-01-08',
    isActive: true,
  },
  {
    id: 'cls5',
    title: 'Labrador Puppies',
    category: 'for-sale',
    subcategory: 'Pets',
    description: 'Beautiful golden Labrador puppies. 8 weeks old, vaccinated and dewormed. Both parents on premises. 3 males, 2 females available.',
    price: 'R3,500 each',
    condition: 'new',
    sellerName: 'Marietjie',
    sellerContact: '+27 82 999 0000',
    location: 'Vaalwater',
    postedDate: '2025-01-13',
    imageUrl: 'https://images.unsplash.com/photo-1591769225440-811ad7d6eab3?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'cls6',
    title: 'Weber Braai - Genesis II',
    category: 'for-sale',
    subcategory: 'Home & Garden',
    description: '4-burner gas braai with side burner. Cover included. Excellent condition, barely used. Relocating, must sell.',
    price: 'R8,500',
    condition: 'used',
    sellerName: 'Andre',
    sellerContact: '+27 83 123 4567',
    location: 'Vaalwater',
    postedDate: '2025-01-11',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'cls7',
    title: 'Wanted: Old Tractor for Parts',
    category: 'wanted',
    subcategory: 'Farm Equipment',
    description: 'Looking for non-running Massey Ferguson 135 or similar for parts. Cash buyer.',
    condition: 'other',
    sellerName: 'Danie',
    sellerContact: '+27 71 234 5678',
    location: 'Waterberg District',
    postedDate: '2025-01-09',
    isActive: true,
  },
  {
    id: 'cls8',
    title: 'Electrician Services',
    category: 'services',
    subcategory: 'Home Services',
    description: 'Qualified electrician. COC certificates, fault finding, new installations, solar systems. Available 7 days.',
    condition: 'other',
    sellerName: 'Spark Electric',
    sellerContact: '+27 82 345 6789',
    location: 'Vaalwater, Modimolle, Lephalale',
    postedDate: '2025-01-07',
    isActive: true,
  },
  {
    id: 'cls9',
    title: 'Bosch Washing Machine',
    category: 'for-sale',
    subcategory: 'Appliances',
    description: 'Front loader, 8kg. 2 years old, still under warranty. Selling due to upgrade. Perfect working condition.',
    price: 'R4,200',
    condition: 'used',
    sellerName: 'Elsa',
    sellerContact: '+27 72 456 7890',
    location: 'Vaalwater',
    postedDate: '2025-01-15',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'cls10',
    title: 'Camping Trailer',
    category: 'for-sale',
    subcategory: 'Outdoor',
    description: 'Jurgens XT140. 2018 model, full tent, fridge, 2-plate gas stove. Papers in order. Perfect bushveld camping.',
    price: 'R95,000',
    condition: 'used',
    sellerName: 'Kobus',
    sellerContact: '+27 83 567 8901',
    location: 'Vaalwater',
    postedDate: '2025-01-06',
    imageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'cls11',
    title: 'Free: Building Rubble',
    category: 'other',
    subcategory: 'Free Stuff',
    description: 'Building rubble from renovation. You collect, you keep. Good for filling or road repair. About 3 bakkie loads.',
    condition: 'other',
    sellerName: 'Thabo',
    sellerContact: '+27 76 678 9012',
    location: 'Vaalwater',
    postedDate: '2025-01-14',
    isActive: true,
  },
  {
    id: 'cls12',
    title: 'Transport Services',
    category: 'services',
    subcategory: 'Transport',
    description: 'Bakkie and trailer available for local deliveries and transport. Furniture, building materials, livestock. Reasonable rates.',
    condition: 'other',
    sellerName: 'Lucky Transport',
    sellerContact: '+27 71 789 0123',
    location: 'Vaalwater & surrounds',
    postedDate: '2025-01-10',
    isActive: true,
  },
  {
    id: 'cls13',
    title: 'Wooden Dining Table + 6 Chairs',
    category: 'for-sale',
    subcategory: 'Furniture',
    description: 'Solid kiaat dining set. Table extends to seat 8. Some minor scratches but very good condition overall.',
    price: 'R12,000',
    condition: 'used',
    sellerName: 'Maria',
    sellerContact: '+27 82 890 1234',
    location: 'Vaalwater',
    postedDate: '2025-01-12',
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'cls14',
    title: 'Wanted: House Sitter',
    category: 'wanted',
    subcategory: 'Services Wanted',
    description: 'Looking for reliable house sitter for 3 weeks in March. Must be comfortable with 2 dogs and basic garden watering.',
    condition: 'other',
    sellerName: 'The Smiths',
    sellerContact: '+27 83 901 2345',
    location: 'Vaalwater',
    postedDate: '2025-01-11',
    isActive: true,
  },
  {
    id: 'cls15',
    title: 'Riding Lawn Mower',
    category: 'for-sale',
    subcategory: 'Garden Equipment',
    description: 'John Deere E100. 42-inch deck, 2020 model. 180 hours. Fully serviced. Ideal for large properties.',
    price: 'R42,000',
    condition: 'used',
    sellerName: 'Hennie',
    sellerContact: '+27 72 012 3456',
    location: 'Vaalwater',
    postedDate: '2025-01-08',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
];

export const PROPERTIES: Property[] = [
  {
    id: 'prop1',
    title: 'Bushveld Smallholding with Views',
    listingType: 'sale',
    propertyType: 'farm',
    bedrooms: 3,
    bathrooms: 2,
    size: 50000,
    price: 'R3,200,000',
    description: 'Beautiful 5-hectare smallholding with established gardens, borehole, and stunning mountain views. Main house has 3 bedrooms, 2 bathrooms, open-plan living. Separate staff quarters. Perfect weekend retreat or permanent residence.',
    address: 'R517, Vaalwater',
    lat: -24.29,
    lng: 28.11,
    features: ['Borehole', 'Staff quarters', 'Mountain views', 'Established garden', 'Carport', 'Prepaid electricity'],
    agentName: 'Waterberg Properties',
    agentContact: '+27 14 755 4321',
    postedDate: '2025-01-05',
    imageUrls: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: true,
  },
  {
    id: 'prop2',
    title: 'Modern Family Home in Town',
    listingType: 'sale',
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 3,
    size: 280,
    price: 'R2,450,000',
    description: 'Spacious 4-bedroom home in secure estate. Modern finishes, double garage, swimming pool, and landscaped garden. Walking distance to school and shops.',
    address: 'Leopard Ridge Estate, Vaalwater',
    lat: -24.30,
    lng: 28.12,
    features: ['Swimming pool', 'Double garage', 'Security estate', 'Landscaped garden', 'Fiber internet', 'Solar geyser'],
    agentName: 'RE/MAX Bushveld',
    agentContact: '+27 82 555 1234',
    postedDate: '2025-01-08',
    imageUrls: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: true,
  },
  {
    id: 'prop3',
    title: 'Vacant Land - Game Farm Potential',
    listingType: 'sale',
    propertyType: 'land',
    size: 500000,
    price: 'R4,500,000',
    description: '50 hectares of pristine bushveld. Ideal for game farming or eco-tourism development. Existing borehole and basic infrastructure. Borders conservancy.',
    address: 'R510, Waterberg',
    lat: -24.25,
    lng: 28.08,
    features: ['Borehole', 'Borders conservancy', 'Game potential', 'Road frontage', 'Electricity nearby'],
    agentName: 'Farm & Land Sales',
    agentContact: '+27 83 666 7890',
    postedDate: '2025-01-10',
    imageUrls: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'prop4',
    title: 'Cozy Cottage for Rent',
    listingType: 'rent',
    propertyType: 'house',
    bedrooms: 2,
    bathrooms: 1,
    size: 85,
    price: 'R6,500 per month',
    description: 'Charming 2-bedroom cottage available for long-term rental. Fully furnished, includes water and basic garden maintenance. Pet-friendly. Ideal for single person or couple.',
    address: 'Vaalwater Village',
    features: ['Furnished', 'Pet-friendly', 'Water included', 'Garden maintenance', 'Carport'],
    agentName: 'Direct from owner',
    agentContact: '+27 72 888 9999',
    postedDate: '2025-01-12',
    imageUrls: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'prop5',
    title: 'Commercial Property - Main Road',
    listingType: 'sale',
    propertyType: 'commercial',
    size: 450,
    price: 'R1,800,000',
    description: 'Prime commercial property on Vaalwater main road. Currently configured as retail space with storage. High visibility location with ample parking.',
    address: 'Main Road, Vaalwater',
    lat: -24.295,
    lng: 28.115,
    features: ['High visibility', 'Ample parking', '3-phase power', 'Alarm system', 'Air conditioning'],
    agentName: 'Waterberg Properties',
    agentContact: '+27 14 755 4321',
    postedDate: '2025-01-06',
    imageUrls: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'prop6',
    title: 'Lodge Opportunity - Turnkey',
    listingType: 'sale',
    propertyType: 'commercial',
    bedrooms: 8,
    bathrooms: 8,
    size: 1200,
    price: 'R12,500,000',
    description: 'Operating game lodge with 8 luxury chalets. Includes all furniture, equipment, and vehicles. Current bookings transfer to new owner. Staff in place. Full financials available to serious buyers.',
    address: 'Waterberg Biosphere',
    lat: -24.20,
    lng: 28.05,
    features: ['Turnkey operation', 'Swimming pool', 'Boma', 'Game vehicles', 'Staff quarters', 'Conference facility', 'Liquor license'],
    agentName: 'Tourism Properties SA',
    agentContact: '+27 82 111 3333',
    postedDate: '2025-01-01',
    imageUrls: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: true,
  },
  {
    id: 'prop7',
    title: 'Starter Home - Great Value',
    listingType: 'sale',
    propertyType: 'house',
    bedrooms: 2,
    bathrooms: 1,
    size: 95,
    price: 'R850,000',
    description: 'Neat 2-bedroom home perfect for first-time buyers or investors. Recently painted, new roof. Close to schools and amenities.',
    address: 'Extension 2, Vaalwater',
    features: ['New roof', 'Walled yard', 'Close to schools', 'Investment potential'],
    agentName: 'Budget Properties',
    agentContact: '+27 71 444 5555',
    postedDate: '2025-01-11',
    imageUrls: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'prop8',
    title: 'Office Space to Rent',
    listingType: 'rent',
    propertyType: 'commercial',
    size: 120,
    price: 'R8,000 per month',
    description: 'Professional office space in Vaalwater business center. Air-conditioned, fiber internet ready. Shared reception and kitchen facilities. Ample parking.',
    address: 'Vaalwater Business Park',
    features: ['Air conditioning', 'Fiber ready', 'Shared reception', 'Parking', 'Security'],
    agentName: 'Vaalwater Rentals',
    agentContact: '+27 14 755 6666',
    postedDate: '2025-01-09',
    imageUrls: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
  {
    id: 'prop9',
    title: 'Riverfront Plot',
    listingType: 'sale',
    propertyType: 'land',
    size: 20000,
    price: 'R1,200,000',
    description: '2 hectares with 150m river frontage. Cleared building site with approved plans. Borehole and electricity on site. Rare opportunity.',
    address: 'Mokolo River, Vaalwater',
    lat: -24.28,
    lng: 28.10,
    features: ['River frontage', 'Approved plans', 'Borehole', 'Electricity', 'Private access'],
    agentName: 'Exclusive Estates',
    agentContact: '+27 82 777 8888',
    postedDate: '2025-01-04',
    imageUrls: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: true,
  },
  {
    id: 'prop10',
    title: 'Flat to Rent in Vaalwater',
    listingType: 'rent',
    propertyType: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    size: 45,
    price: 'R4,500 per month',
    description: 'Bachelor flat with open-plan kitchen and living area. Separate bedroom. Secure parking. Water included. Available immediately.',
    address: 'Central Vaalwater',
    features: ['Secure parking', 'Water included', 'Immediately available', 'Close to shops'],
    agentName: 'Direct from owner',
    agentContact: '+27 83 222 1111',
    postedDate: '2025-01-14',
    imageUrls: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
    ],
    isFeatured: false,
  },
];

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann1',
    title: 'LOST DOG - Brown Boerboel',
    category: 'lost-found',
    description: 'Large brown Boerboel male, answers to "Brak". Last seen near Spar on Monday 13 Jan around 5pm. Wearing red collar. Reward offered for safe return.',
    contactName: 'Van Wyk Family',
    contactMethod: '+27 82 999 1234',
    location: 'Vaalwater Town Centre',
    postedDate: '2025-01-14',
    expiryDate: '2025-01-28',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    id: 'ann2',
    title: 'Water Restrictions - Level 2',
    category: 'alert',
    description: 'Due to low dam levels, Level 2 water restrictions are now in effect. No garden watering between 10am-4pm. Car washing with buckets only. Swimming pools may not be topped up.',
    contactName: 'Vaalwater Municipality',
    contactMethod: '+27 14 755 1000',
    location: 'All Vaalwater',
    postedDate: '2025-01-10',
    expiryDate: '2025-03-31',
    isActive: true,
  },
  {
    id: 'ann3',
    title: 'Road Closure - R517',
    category: 'alert',
    description: 'R517 will be closed for repairs between km 42-45 from 20-24 January. Please use alternative routes via Modimolle or Lephalale road.',
    contactName: 'SANRAL',
    contactMethod: '0800 725 725',
    location: 'R517 Waterberg',
    postedDate: '2025-01-12',
    expiryDate: '2025-01-25',
    isActive: true,
  },
  {
    id: 'ann4',
    title: 'FOUND: Set of Keys',
    category: 'lost-found',
    description: 'Set of keys found outside the library on Thursday. Has Toyota key fob and several house keys. Contact to identify and collect.',
    contactName: 'Vaalwater Library',
    contactMethod: '+27 14 755 2222',
    location: 'Vaalwater Library',
    postedDate: '2025-01-09',
    expiryDate: '2025-02-09',
    isActive: true,
  },
  {
    id: 'ann5',
    title: 'Neighbourhood Watch Meeting',
    category: 'community-notice',
    description: 'Monthly neighbourhood watch meeting this Thursday at 18:00. Topics: recent incidents, patrol schedules, new members welcome. Bring your own chair.',
    contactName: 'Jannie - NHW Coordinator',
    contactMethod: '+27 72 333 4444',
    location: 'NG Kerk Hall, Vaalwater',
    postedDate: '2025-01-13',
    expiryDate: '2025-01-16',
    isActive: true,
  },
  {
    id: 'ann6',
    title: 'Clinic Mobile Unit - Free Services',
    category: 'community-notice',
    description: 'Department of Health mobile clinic visiting Vaalwater on 25 January. Free basic health checks, vaccinations, and chronic medication collection. No appointment needed.',
    contactName: 'Limpopo Health Department',
    contactMethod: '0800 212 345',
    location: 'Vaalwater Community Hall',
    postedDate: '2025-01-11',
    expiryDate: '2025-01-26',
    isActive: true,
  },
  {
    id: 'ann7',
    title: 'School Registration Open',
    category: 'community-notice',
    description: 'Vaalwater Primary School accepting applications for 2025. Bring birth certificate, immunisation card, and proof of residence. Office hours: 8am-2pm weekdays.',
    contactName: 'School Secretary',
    contactMethod: '+27 14 755 3333',
    location: 'Vaalwater Primary School',
    postedDate: '2025-01-08',
    expiryDate: '2025-02-28',
    isActive: true,
  },
  {
    id: 'ann8',
    title: 'Load Shedding Update',
    category: 'alert',
    description: 'Vaalwater has been moved to Group 4 for load shedding schedules. Check EskomSePush app for accurate times. Stages announced daily at 5pm.',
    contactName: 'Eskom',
    contactMethod: '0860 037 566',
    location: 'Vaalwater Area',
    postedDate: '2025-01-15',
    expiryDate: '2025-12-31',
    isActive: true,
  },
];

// Vaalwater-specific exports for multi-tenant config system
// These are aliases to the main exports above
export const VAALWATER_SECTORS = SECTORS;
export const VAALWATER_BUSINESSES = BUSINESSES;
export const VAALWATER_JOBS = JOBS;
export const VAALWATER_EVENTS = EVENTS;
export const VAALWATER_CLASSIFIEDS = CLASSIFIEDS;
export const VAALWATER_PROPERTIES = PROPERTIES;
export const VAALWATER_ANNOUNCEMENTS = ANNOUNCEMENTS;
